import * as mongoose from "mongoose";

export interface IConceptos extends mongoose.Document {
    empresa_id:string ,
    codigo?:string ,
    referencia?: string ,
    nombre: string,
    descripcion?: string,
    talla?: string,
    color?: string,
    descuento?:number,
    serial_estatico?: number,
    serial_dinamico?: number,
    existencia_minima?: number,
    existencia_maxima?: number,
    tipos_conceptos_id: string,
    ubicacion_id?:  string,
    costo?: number,
    ultimo_costo?: number,
    costo_mayor?: number,
    costo_promedio?: number,
    grupos_id?: string,
    subgrupos_id?: string,
    unidades_id?: string,
    marcas_id?: string,
    estado?: number,
    pvp?:number,
    precio_a:number,
    precion_b?:number,
    precio_dolar:number,
    utilidad?:number,
    utiliad_a?:number,
    utilidad_b?:number,
    utilidad_c?:number,
    utilidad_dolar?:number,
    costo_dolar:number,
    precio_variante?:number,
    retiene?: number,
    farm_principio_activo_id?: number,
    imagen?:string,
    costo_adicional?: number,
    costo_adicional2?:number,
    cant_ensamblado?:number,
    licor?: number,
    porcentaje?:number,
    visible_pv?: number,
    visible_web?: number,
    rest_areas_id?: number ,
    setcortesia?: number,
    exento?: number,
    merma?: number,
    exitencia_c?: number,
    obviar_ajuste?: number,
    iva?:number,
}
  
export const ConceptoSchema = new mongoose.Schema({
    empresa_id:{ type: String, required: true },
    codigo:{ type: String, required: false },
    referencia: { type: String, required: false},
    nombre: { type: String, required: true },
    descripcion:{ type: String, required: true },
    talla: { type: String, required: false },
    color: { type: String, required: false },
    descuento:{ type: Number, required: false },
    serial_estatico: { type: Number, required: false },
    serial_dinamico: { type: Number, required: false },
    existencia_minima: { type: Number, required: false },
    existencia_maxima: { type: Number, required: false },
    tipos_conceptos_id: { type: String, required: true },
    ubicacion_id: { type: String, required: false},
    costo: { type: Number, required: false },
    ultimo_costo: { type: Number, required: false },
    costo_mayor:{ type: Number, required: false },
    costo_promedio: { type: Number, required: false },
    grupos_id:{ type: String, required: false },
    subgrupos_id: { type: String, required: false },
    unidades_id: { type: String, required: false},
    marcas_id: { type: String, required: false},
    estado: { type: Number, required: false },
    pvp:{ type: Number, required: false },
    precio_a:{ type: Number, required: true },
    precion_b:{ type: Number, required: false },
    precio_dolar:{ type: Number, required: true },
    utilidad:{ type: Number, required: false },
    utiliad_a:{ type: Number, required: false },
    utilidad_b:{ type: Number, required: false },
    utilidad_c:{ type: Number, required: false },
    utilidad_dolar:{ type: Number, required: false },
    costo_dolar:{type: Number, required: false },
    precio_variante:{ type: Number, required: false },
    retiene: { type: Number, required: false },
    farm_principio_activo_id: { type: Number, required: false },
    imagen:{ type: String, required: true},
    costo_adicional: { type: Number, required: false },
    costo_adicional2:{ type: Number, required: false },
    cant_ensamblado:{ type: Number, required: false },
    licor: { type: Number, required: false },
    porcentaje:{ type: Number, required: false },
    visible_pv: { type: Number, required: false },
    visible_web:{ type: Number, required: false },
    rest_areas_id: { type: Number, required: false },
    setcortesia: { type: Number, required: false },
    exento: { type: Number, required: false },
    merma: { type: Number, required: false },
    exitencia_c: { type: Number, required: false },
    obviar_ajuste: { type: Number, required: false },
    iva:{ type: Number, required: false },
});
  

const Conceptos = mongoose.model<IConceptos>("Conceptos", ConceptoSchema);

export default Conceptos;